require 'cap_bootstrap/recipes/base'
require 'cap_bootstrap/recipes/check'
require 'cap_bootstrap/recipes/nginx'
require 'cap_bootstrap/recipes/nodejs'
require 'cap_bootstrap/recipes/postgresql'
require 'cap_bootstrap/recipes/rbenv'
require 'cap_bootstrap/recipes/unicorn'
require 'cap_bootstrap/recipes/utilities'
